import Head from "next/head";
import Entry from "../components/Entry";
import Navbar from "../components/Navbar";
import { FaAngleDown } from "react-icons/fa";
import { AiFillPlusCircle } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="px-4 py-6">
        <div className="flex justify-between mt-20 mb-8">
          <div>
            <h2 className="text-lg">Invoices</h2>
            <span className="text-sm text-grey-color">3 invoices</span>
          </div>
          <div className="flex items-center space-x-2">
            <span>Filter</span>
            <button>
              <FaAngleDown size={18} className="text-secondary-color" />
            </button>
            <button className="flex items-center justify-between w-20 px-2 py-1 font-semibold rounded-full bg-secondary-color">
              <AiFillPlusCircle size={30} />
              <span>New</span>
            </button>
          </div>
        </div>
        <div className="space-y-4">
          <Entry />
          <Entry />
          <Entry />
        </div>
      </main>
    </div>
  );
}
