import Head from "next/head";
import Card from "../components/Card";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="px-6 py-8 mt-20">
        <Header />
        <main className="space-y-5">
          <Card />
          <Card />
          <Card />
        </main>
      </div>
    </div>
  );
}
