import Head from "next/head";
import Entry from "../components/Entry";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="relative w-3/4 h-screen m-auto bg-red-400 top-20">
        <Entry />
      </div>
    </div>
  );
}
